package com.jorzet.truedareshot.models.error

/**
 * @author Jorge Zepeda Tinoco
 * @email jorzet.94@gmail.com
 * @date 20/05/19
 */

enum class ErrorType {
    ERROR_NOT_USER,
    EMAIL_NOT_UPDATED,
    PASSWORD_NOT_UPDATED,
    USER_NOT_SENDED,
    SELECTED_SCHOOLS_NOT_SENDED,
    ANSWERED_EXAMS_NOT_SENDED,
    ANSWERED_MODULES_NOT_SENDED,
    ANSWERED_QUESTIONS_NOT_SENDED,
    FACEBOOK_NOT_LINKED,
    FACEBOOK_NOT_SIGNED_IN,
    GOOGLE_NOT_LINKED,
    GOOGLE_NOT_SIGNED_IN,
    NETWORK_ERROR,
    QUESTIONS_ERROR,
    NULL_RESPONSE,
    CANNOT_LOGIN,
    CANNOT_DOWNLOAD_CONTENT,
    CANNOT_DOWNLOAD_CONTENT_FILE_NOT_FOUND
}